### ISSUE TITLE
THANK YOU!!

### ISSUE THREAD

**Issue by fnfporterhi** [LEVIXDDLMAO/FNF-Asset-Folder-CLEAN#1]
FINALLY I CAN FINISH MY SHAGGY PORT!!!

**Comment by LEVIXDDLMAO** [comment]
dude this is for mod ports NOT FUCKING SHAGGY

**Comment by fnfporterhi** [comment]
I WAS GONNA USE IT :(

**Comment by fnfporterhi** [comment]
MY ASSETS FOLDER IS THE PROBLEM UNTIL I CAN GET TO A WINDOWS PC I HAVE TO WAIT

**Comment by LEVIXDDLMAO** [comment]
YEAH BUT IF YOU DO IT BREAKS THE WHOLE DAMN GAME

**Comment by LEVIXDDLMAO** [comment]
AAAAAAAAAAAAAAAAAAAa

**Comment by fnfporterhi** [comment]
AAAAAAAAAA

**Comment by LEVIXDDLMAO** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by fnfporterhi** [comment]
WHY ARE WE SCREAMING

**Comment by LEVIXDDLMAO** [comment]
BECAUSE AAAAAAAAAa

**Comment by fnfporterhi** [comment]
WHY BECAUSE THAT
